name: Deploy to Staging for Production Release w/Swap

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'app-name-here'
  AZURE_WEBAPP_SLOT: 'staging' # 'production' || 'staging' || 'qa' || 'test'
  AZURE_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_secretid }}
  DOT_NET_VERSION: '6.0.x'
  DEPLOY_APP_FOLDER: 'dotnetcorewebapp'

jobs:
  build-and-deploy:
    name: 'Build And Deploy to Azure'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up .NET Core'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOT_NET_VERSION }}
          include-prerelease: true

      - name: 'Install Dependencies'
        run: dotnet restore
        
      - name: 'Build with dotnet'
        run: dotnet build --configuration Release
        
      - name: 'Test'
        run: dotnet test --no-restore --verbosity normal
        
      - name: 'dotnet publish'
        run: | 
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/${{ env.DEPLOY_APP_FOLDER }}
          
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/${{ env.DEPLOY_APP_FOLDER }}
